# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyRSzTVEyq8SuH9NNrIO4r_n4WCVK2or
"""

import cv2
import numpy as np
import json
import tensorflow as tf

# ─────────────────────────────
# 0) 설정
# ─────────────────────────────
IMAGE_PATH   = '/content/schedule4.jpg'      # 이미지 경로
TFLITE_MODEL = 'dne_classifier.tflite'       # 3-class TFLite 모델 경로
WHITE_THRESH = 0.86                          # 빈 셀 판단 임계치
CLASS_LABELS = ['D', 'N', 'E']               # 3-class
HEADER_SKIP_Y = 2   # 상단 헤더(번호+이름) 행 개수
HEADER_SKIP_X = 1   # 왼쪽 헤더(이름) 열 개수
DEBUG_VIS = True    # 표 전체 box 시각화 저장

# ─────────────────────────────
# 1) 라인 감지 + 셀 좌표 추출
# ─────────────────────────────
def get_table_cells(img_path, header_skip_y=2, header_skip_x=1, vis_path="table_detected.png"):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    assert img is not None, f"Image not found at {img_path}"

    # Binarize (invert + Otsu)
    _, binary = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    # Morphology to extract border lines
    h_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (100, 1))
    v_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 100))
    h_lines = cv2.morphologyEx(binary, cv2.MORPH_OPEN, h_kernel)
    v_lines = cv2.morphologyEx(binary, cv2.MORPH_OPEN, v_kernel)

    def find_seps(mask, axis, ratio=0.5):
        proj = mask.sum(axis=0) if axis=='x' else mask.sum(axis=1)
        thresh = proj.max() * ratio
        idx = np.where(proj > thresh)[0]
        groups = np.split(idx, np.where(np.diff(idx) > 1)[0] + 1)
        return sorted(int(np.median(g)) for g in groups if len(g) > 0)

    x_seps = find_seps(v_lines, 'x', 0.5)
    y_seps = find_seps(h_lines, 'y', 0.5)

    # (시각화)
    if vis_path:
        img_vis = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        for y in y_seps:
            cv2.line(img_vis, (x_seps[0], y), (x_seps[-1], y), (0,0,255), 2)
        for x in x_seps:
            cv2.line(img_vis, (x, y_seps[0]), (x, y_seps[-1]), (0,0,255), 2)
        cv2.imwrite(vis_path, img_vis)
        print(f"Table lines visualization saved: {vis_path}")

    # (좌표 반환)
    data_rows = list(zip(y_seps[header_skip_y-1:-1], y_seps[header_skip_y:]))

    data_cols = list(zip(x_seps[header_skip_x:-1], x_seps[header_skip_x+1:]))
    return img, data_rows, data_cols

# ─────────────────────────────
# 2) 셀 crop + 리사이즈
# ─────────────────────────────
def tight_crop_and_resize(cell_img, out_size=(32,32)):
    if cell_img is None or cell_img.size == 0:
        return np.full(out_size, 255, dtype=np.uint8)
    # cell_img: 2D gray
    _, threshed = cv2.threshold(cell_img, 200, 255, cv2.THRESH_BINARY)
    inv = 255 - threshed
    coords = cv2.findNonZero(inv)
    if coords is not None:
        x, y, w, h = cv2.boundingRect(coords)
        cropped = cell_img[y:y+h, x:x+w]
    else:
        cropped = cell_img
    resized = cv2.resize(cropped, out_size)
    return resized

# ─────────────────────────────
# 3) 셀 분류 함수
# ─────────────────────────────
def classify_dne(cell_img, interpreter, input_details, output_details, debug=False, r=0, c=0):
    tight_img = tight_crop_and_resize(cell_img)
    white_ratio = np.mean(tight_img > 220)
    if debug:
        cv2.imwrite(f'debug_cell_r{r}_c{c}.png', tight_img)
    if white_ratio > WHITE_THRESH:
        if debug: print("Blank cell detected: white_ratio=", white_ratio)
        return '-'
    h, w = input_details[0]['shape'][1:3]
    inp = tight_img.astype(np.float32) / 255.0
    sample = inp.reshape(1, h, w, 1)
    interpreter.set_tensor(input_details[0]['index'], sample)
    interpreter.invoke()
    out = interpreter.get_tensor(output_details[0]['index'])[0]
    if debug: print(f"Probabilities: D={out[0]:.3f}, N={out[1]:.3f}, E={out[2]:.3f}")
    idx = np.argmax(out)
    label = CLASS_LABELS[idx]
    if debug: print("Predicted label:", label)
    return label

# ─────────────────────────────
# 4) 메인 실행 & JSON 변환
# ─────────────────────────────
def main():
    # (1) 셀 경계 자동 추출
    img, data_rows, data_cols = get_table_cells(
        IMAGE_PATH, header_skip_y=2, header_skip_x=1, vis_path="table_detected.png"
    )

    # (2) TFLite 모델 준비
    interpreter = tf.lite.Interpreter(model_path=TFLITE_MODEL)
    interpreter.allocate_tensors()
    input_details  = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # (3) 셀 순회하며 분류
    result = {}
    debug_count = 0
    for r, (y1, y2) in enumerate(data_rows):
        row_dict = {}
        for c, (x1, x2) in enumerate(data_cols):
            cell_img = img[y1:y2, x1:x2]
            debug = (debug_count < 30)
            # 파일 이름에 좌표도 추가!
            debug = (debug_count < 30)
            val = classify_dne(cell_img, interpreter, input_details, output_details, debug=debug, r=r, c=c)
            row_dict[str(c+1)] = val
            if debug: debug_count += 1
        result[str(r+1)] = row_dict


    json_str = json.dumps(result, ensure_ascii=False, indent=2)
    print(json_str)
    with open('schedule_inferred.json', 'w', encoding='utf-8') as f:
        f.write(json_str)
    print("schedule_inferred.json 생성 완료")

if __name__ == '__main__':
    main()